version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    networks:
      - my_network

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
